/* Auth */
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

/* Classroom */
export const GET_CLASS_LIST = "GET_CLASS_LIST";
export const GET_CLASS_LIST_SUCCESS = "GET_CLASS_LIST_SUCCESS";
export const GET_CLASS_LIST_FAILURE = "GET_CLASS_LIST_FAILURE";

/* Get Class Info */
export const GET_CLASS_INFO = "GET_CLASS_INFO";
export const GET_CLASS_INFO_SUCCESS = "GET_CLASS_INFO_SUCCESS";
export const GET_CLASS_INFO_FAILURE = "GET_CLASS_INFO_FAILURE";

/* Get Class_Student */
export const GET_CLASS_STUDENT = "GET_CLASS_STUDENT";
export const GET_CLASS_STUDENT_SUCCESS = "GET_CLASS_STUDENT_SUCCESS";
export const GET_CLASS_STUDENT_FAILURE = "GET_CLASS_STUDENT_FAILURE";

/* Notice */
export const GET_NOTICE = "GET_NOTICE";
export const GET_NOTICE_SUCCESS = "GET_NOTICE_SUCCESS";
export const GET_NOTICE_FAILURE = "GET_NOTICE_FAILURE";

export const POST_NOTICE = "POST_NOTICE";
export const POST_NOTICE_SUCCESS = "POST_NOTICE_SUCCESS";
export const POST_NOTICE_FAILURE = "POST_NOTICE_FAILURE";

export const DELETE_NOTICE = "DELETE_NOTICE";
export const DELETE_NOTICE_SUCCESS = "DELETE_NOTICE_SUCCESS";
export const DELETE_NOTICE_FAILURE = "DELETE_NOTICE_FAILURE";

/* Project (Kanbanboard) */
export const SET_PROJECT = "SET_PROJECT";

export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";

export const POST_PROJECT = "POST_PROJECT";
export const POST_PROJECT_SUCCESS = "POST_PROJECT_SUCCESS";
export const POST_PROJECT_FAILURE = "POST_PROJECT_FAILURE";

export const PUT_PROJECT = "PUT_PROJECT";
export const PUT_PROJECT_SUCCESS = "PUT_PROJECT_SUCCESS";
export const PUT_PROJECT_FAILURE = "PUT_PROJECT_FAILURE";

export const GET_STANDBY_PROJECT = "GET_STANDBY_PROJECT";
export const GET_STANDBY_PROJECT_SUCCESS = "GET_STANDBY_PROJECT_SUCCESS";
export const GET_STANDBY_PROJECT_FAILURE = "GET_STANDBY_PROJECT_FAILURE";

/* Kanban */
export const GET_KANBAN_LIST = "GET_KANBAN_LIST";
export const GET_KANBAN_LIST_SUCCESS = "GET_KANBAN_LIST_SUCCESS";
export const GET_KANBAN_LIST_FAILURE = "GET_KANBAN_LIST_FAILURE";

export const GET_KANBAN = "GET_KANBAN";
export const GET_KANBAN_SUCCESS = "GET_KANBAN_SUCCESS";
export const GET_KANBAN_FAILURE = "GET_KANBAN_FAILURE";

export const POST_KANBAN = "POST_KANBAN";
export const POST_KANBAN_SUCCESS = "POST_KANBAN_SUCCESS";
export const POST_KANBAN_FAILURE = "POST_KANBAN_FAILURE";

export const PUT_KANBAN_INFO = "PUT_KANBAN_INFO";
export const PUT_KANBAN_INFO_SUCCESS = "PUT_KANBAN_INFO_SUCCESS";
export const PUT_KANBAN_INFO_FAILURE = "PUT_KANBAN_INFO_FAILURE";

export const PUT_KANBAN_STATUS = "PUT_KANBAN_STATUS";
export const PUT_KANBAN_STATUS_SUCCESS = "PUT_KANBAN_STATUS_SUCCESS";
export const PUT_KANBAN_STATUS_FAILURE = "PUT_KANBAN_STATUS_FAILURE";

export const DELETE_KANBAN = "DELETE_KANBAN";
export const DELETE_KANBAN_SUCCESS = "DELETE_KANBAN_SUCCESS";
export const DELETE_KANBAN_FAILURE = "DELETE_KANBAN_FAILURE";

/* Kanban Feedback */
export const GET_FEEDBACK = "GET_FEEDBACK";
export const GET_FEEDBACK_SUCCESS = "GET_FEEDBACK_SUCCESS";
export const GET_FEEDBACK_FAILURE = "GET_FEEDBACK_FAILURE";

export const POST_FEEDBACK = "POST_FEEDBACK";
export const POST_FEEDBACK_SUCCESS = "POST_FEEDBACK_SUCCESS";
export const POST_FEEDBACK_FAILURE = "POST_FEEDBACK_FAILURE";

/* Get Message */
export const GET_MESSAGE = "GET_MESSAGE";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MESSAGE_FAILURE = "GET_MESSAGE_FAILURE";

export const PUT_READ_MESSAGE = "PUT_READ_MESSAGE";

/* Get SearchProject */
export const GET_SEARCH_PROJECT = "GET_SEARCH_PROJECT";
export const GET_SEARCH_PROJECT_SUCCESS = "GET_SEARCH_PROJECT_SUCCESS";
export const GET_SEARCH_PROJECT_FAILURE = "GET_SEARCH_PROJECT_FAILURE";
